### ISSUE TITLE
Error on Manjaro 19.0.2 - PKGVER

### ISSUE THREAD

**Issue by xavatar** [Fincer/dxvk-wine-autobuilder#1] opened 2020-03-19 10:37 UTC
Hello,

I cant use your script, i have a error with PKGVER : 

==> Starting pkgver()...
==> ERROR: pkgver is not allowed to contain colons, forward slashes, hyphens or whitespace.
==> ERROR: pkgver() generated an invalid version:   -> Setting Wine versions...
stg.5.4.r8.g53b02cd0+wine.wine.5.4.r128.gc43998cb51

Thx for your reply.

**Comment by Fincer** [comment] 2020-03-19 13:15
Hi,

thanks for reporting the issue, I'll investigate this soon!

**Comment by Fincer** [comment] 2020-04-17 21:37
Finally I had my moment to take a look at this issue.

The fix is extremely simple: It looks like the root cause are recent changes `pkgver()` behavior as it assumes a single output string to be printed without *any* additional messages. Originally, [the Wine PKGBUILD file](https://github.com/Fincer/dxvk-wine-autobuilder/blob/master/arch/0-wine-staging-git/PKGBUILD) had an additional message in `pkgver()` which caused this issue.

The full output string, as interpreted by the newer `pkgver()` function was

```
Setting Wine versions...
<Wine version string>
```

whereas the correct syntax simply uses

```
<Wine version string>
```

as an output.

Simply removing `Setting Wine versions...` should fix the issue.

Fixed by commit: https://github.com/Fincer/dxvk-wine-autobuilder/commit/90aaab9b08cffb85d468dfb9f46eca65b8cba799

**Comment by xavatar** [comment] 2020-04-18 07:46
Ok ty for the reply !

**Comment by Fincer** [comment] 2020-04-18 09:22
Np, thanks for reporting the issue.  I apologize my "soon" was more than expected.

I guess I can close the issue now. Just let me know if you had more issues with the script bundle.

**Closed as completed by Fincer** 2020-04-18 09:22 UTC
